apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: pawzaroo
  labels:
    app: api
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: pawzaroo
spec:
  type: ClusterIP
  selector: { app: api }
  ports:
    - name: http
      port: 8080
      targetPort: http
