apiVersion: v1
kind: Secret
metadata:
  name: pawzaroo-secrets
  namespace: pawzaroo
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_ME"
  JWT_SIGNING_KEY: "REPLACE_ME_WITH_LONG_RANDOM"
  STORAGE_ACCESS_KEY: "minioadmin"
  STORAGE_SECRET_KEY: "minioadmin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pawzaroo-config
  namespace: pawzaroo
data:
  POSTGRES_DB: pawzaroo
  POSTGRES_USER: pawzaroo
  REDIS_HOST: redis
  KAFKA_BROKERS: kafka:9092
  STORAGE_ENDPOINT: http://minio:9000
  STORAGE_BUCKET: pawzaroo-media
